#!/bin/sh

if [ "x$1" = "xclean" ]; then
    echo Cleaning
    make distclean
    rm -f configure Makefile.in depcomp missing Makefile.am aclocal.m4 install-sh
    rm -rf autom4te.cache
    exit
fi
## Generate Makefile.am from ccbuild
PSOURCE=src/metalink.cc
PNAME=`basename "${PSOURCE}" .cc`
VERSION=0.3.6

#Update MD5SUMS, if we have the right tools
which ccbuild && (ccbuild md5 --recursive-include . "${PSOURCE}" > MD5SUMS)

SOURCES=`sed  -r 's/^[a-z0-9]+  //; s/ /\\ /' < MD5SUMS | tr '\n' ' '`

#Write CMakeLists.txt
cat > CMakeLists.txt <<EOF
cmake_minimum_required (VERSION 2.6)
project (${PNAME})
add_definitions(-DVERSION="${VERSION}")
find_package(PkgConfig)

pkg_check_modules(GTKMM REQUIRED gtkmm-2.4)
include_directories(\${GTKMM_INCLUDE_DIRS})
link_directories(\${GTKMM_LIBRARY_DIRS})
link_libraries(\${GTKMM_LIBRARIES} gcrypt)

add_definitions(-std=c++11 )
add_executable(${PNAME} ${SOURCES})
EOF

#Overwrite Makefile.am
cat > Makefile.am <<EOF
AUTOMAKE_OPTIONS = subdir-objects

bin_PROGRAMS = ${PNAME}


#Sources, generated list from ccbuild md5 output
${PNAME}_SOURCES = ${SOURCES}
${PNAME}_LDFLAGS = @LIBGCRYPT_LIBS@
${PNAME}_CXXFLAGS = @LIBGCRYPT_CFLAGS@ -D_LARGEFILE_SOURCE \$(DEPS_CFLAGS)
${PNAME}_LDADD = \$(DEPS_LIBS)
dist_man_MANS = doc/metalink.1
EOF

echo "Running autotools:"
##BOOTSTRAP
echo " aclocal"
aclocal -I /usr/share/autoconf-archive
echo " autoconf"
autoconf
echo " automake"
automake --add-missing


