#!/bin/sh

if [ "x$1" = "xclean" ]; then
    echo Cleaning
    rm -f metalink
    exit
fi

## Generate Makefile.am from ccbuild
PSOURCE=src/metalink.cc
PNAME=`basename "${PSOURCE}" .cc`
VERSION=0.3.6

#Update MD5SUMS, if we have the right tools
which ccbuild && (ccbuild md5 --recursive-include . "${PSOURCE}" > MD5SUMS)

SOURCES=`sed  -r 's/^[a-z0-9]+  //; s/ /\\ /' < MD5SUMS | tr '\n' ' '`

#Write CMakeLists.txt
cat > CMakeLists.txt <<EOF
cmake_minimum_required (VERSION 2.6)
project (${PNAME})
add_definitions(-DVERSION="${VERSION}")
find_package(PkgConfig)

pkg_check_modules(GLIBMM REQUIRED glibmm-2.4)
include_directories(\${GLIBMM_INCLUDE_DIRS})
link_directories(\${GLIBMM_LIBRARY_DIRS})
link_libraries(\${GLIBMM_LIBRARIES} gcrypt)

add_definitions(-std=c++11 )
add_executable(${PNAME} ${SOURCES})

install(TARGETS metalink DESTINATION bin)
EOF
